# Generated by Django 5.2.8 on 2025-11-05 20:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(max_length=10)),
                ('posted_at', models.DateField(default=django.utils.timezone.now)),
                ('main_picture', models.URLField()),
                ('hover_picture', models.URLField(default=models.URLField())),
                ('pictures_list', models.JSONField(default=list)),
                ('is_available', models.BooleanField()),
                ('reviews_qty', models.IntegerField(max_length=10)),
            ],
        ),
    ]
