# Generated by Django 5.2.8 on 2025-11-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='description',
            field=models.CharField(default=models.CharField(default='Some Piece of Scrap', max_length=255), max_length=500),
        ),
        migrations.AddField(
            model_name='good',
            name='title',
            field=models.CharField(default='Some Piece of Scrap', max_length=255),
        ),
    ]
