# Generated by Django 5.2.8 on 2025-11-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_good_description_good_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='brand',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='good',
            name='characteristics',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='good',
            name='reviews_qty',
            field=models.IntegerField(),
        ),
    ]
