# Generated by Django 5.2.8 on 2025-11-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_good_brand_good_characteristics_alter_good_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
