# Generated by Django 5.2.8 on 2025-11-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_good_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
