# Generated by Django 5.2.8 on 2025-11-06 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_good_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=255)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.RenameField(
            model_name='good',
            old_name='brand',
            new_name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='good',
            name='reviews_qty',
        ),
        migrations.AddField(
            model_name='good',
            name='reviews',
            field=models.JSONField(default=list),
        ),
    ]
