# Generated by Django 5.2.8 on 2025-11-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_review_rename_brand_good_manufacturer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipses', models.JSONField(blank=True, default=list)),
                ('cpus', models.JSONField(blank=True, default=list)),
                ('rams', models.JSONField(blank=True, default=list)),
                ('ssds', models.JSONField(blank=True, default=list)),
                ('manufacturers', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.AlterField(
            model_name='good',
            name='characteristics',
            field=models.JSONField(default={'CPU': '', 'IPS': '0"', 'RAM': '0GB', 'SSD': '0GB'}),
        ),
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='good',
            name='hover_picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='pictures_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='good',
            name='reviews',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
