# Generated by Django 5.2.8 on 2025-11-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_savedcharacteristics_alter_good_characteristics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcharacteristics',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='savedcharacteristics',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=10000000, max_digits=8),
        ),
        migrations.AlterField(
            model_name='good',
            name='characteristics',
            field=models.JSONField(default={'CPU': '', 'IPS': '0', 'RAM': '0GB', 'SSD': '0GB'}),
        ),
    ]
