# Generated by Django 5.2.8 on 2025-12-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_savedcharacteristics_max_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='characteristics',
            field=models.JSONField(default={'CPU': '', 'GPU': '', 'RAM': '0GB', 'SSD': '0GB', 'matrix': '0'}),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='savedcharacteristics',
            name='max_price',
            field=models.IntegerField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='savedcharacteristics',
            name='min_price',
            field=models.IntegerField(default=10000000, max_length=8),
        ),
    ]
