# Generated by Django 5.2.8 on 2025-12-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_alter_good_characteristics_alter_good_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedcharacteristics',
            old_name='ipses',
            new_name='gpus',
        ),
        migrations.AddField(
            model_name='savedcharacteristics',
            name='matrixes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
