# Generated by Django 5.2.8 on 2026-01-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_rename_ipses_savedcharacteristics_gpus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
