# Generated by Django 5.2.8 on 2026-01-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_alter_good_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='CPU',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='good',
            name='GPU',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='good',
            name='RAM',
            field=models.CharField(default='0GB', max_length=100),
        ),
        migrations.AddField(
            model_name='good',
            name='screen_diagonal',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='good',
            name='screen_refresh_rate',
            field=models.CharField(default='0Hz', max_length=10),
        ),
        migrations.AddField(
            model_name='good',
            name='storage_capacity',
            field=models.CharField(default='0GB', max_length=100),
        ),
    ]
