# Generated by Django 5.2.8 on 2026-01-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_good_cpu_good_gpu_good_ram_good_screen_diagonal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='characteristics',
        ),
        migrations.RemoveField(
            model_name='savedcharacteristics',
            name='matrixes',
        ),
        migrations.RemoveField(
            model_name='savedcharacteristics',
            name='ssds',
        ),
        migrations.AddField(
            model_name='savedcharacteristics',
            name='screen_diagonals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='savedcharacteristics',
            name='screen_refresh_rates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='savedcharacteristics',
            name='storage_capacities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
